name: SAP Infrastructure Deployment $(sap_system_folder)

parameters:
  - name: sap_system
    displayName: "SAP System configuration name, use the following syntax: ENV-LOCA-VNET-SID"
    type: string
    default: DEV-NOEU-SAP01-EQ2

  - name: environment
    displayName: Workload Environment (DEV, QUA, PRD, ...)
    type: string
    default: DEV

trigger: none

pool:
  name: $[coalesce(variables['POOL'], variables['Agent'])]
  vmImage: ubuntu-latest

extends:
  template: ./resources.yml
  parameters:
    stages:
      - template: deploy\pipelines\03-sap-system-deployment.yaml@sap-automation
        parameters:
          sap_system: ${{ parameters.sap_system }}
          environment: ${{ parameters.environment }}
          sap_automation_repo_path: $(Build.SourcesDirectory)/sap-automation
          config_repo_path: $(Build.SourcesDirectory)/config
